language: python

python:
  - "3.6"

sudo: required

install:
  - pip install coveralls

script:
  - coverage run --source=transparencia_back_token_coveralls setup.py test

after_success:
  - coveralls