language: python

python:
  - "3.6"

sudo: required

virtualenv:
  system_site_packages: true

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=transparencia_api setup.py test

after_success:
  - coveralls